-- Row Level Security を全テーブルで有効化する（ポリシーは追加しない＝デフォルト全拒否）。
-- このアプリはPrisma経由（テーブル所有者ロール）でしか直接DBに繋がないため、
-- RLSを有効にしてもアプリの動作には影響しない（所有者はRLSの制限を受けない）。
-- 影響を受けるのは、SupabaseのREST API（anon/authenticatedロール）経由のアクセスのみで、
-- そちらは全テーブルで完全にブロックされるようになる。

ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Company" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Team" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeamClientRelationship" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CompanyMembership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaidLeaveEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeamMembership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CompanyRelationship" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RelationshipNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffPlacement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CompanyPlacementRate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CompanyPlacementRateVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffTaskRate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffTaskRateVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffNotice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InviteToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Shift" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConflictOverride" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ShiftRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PublicRecruitment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RecruitmentEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkReport" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ContractTemplate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffContract" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffContractWageVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalarySlip" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalarySlipLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SalarySlipIssue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InvoiceLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InvoiceIssue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TeeLedgerEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BankTransferRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StripeCharge" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffPointsLedgerEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PromoItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PromoRedemption" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TodoItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TodoComment" ENABLE ROW LEVEL SECURITY;
