// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations need a direct (unpooled) connection — MIGRATE_DATABASE_URL is
    // that, DATABASE_URL is the pooled one the running app uses. Falls back to
    // DATABASE_URL where MIGRATE_DATABASE_URL isn't set (local dev).
    url: process.env["MIGRATE_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
